# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{oa-webmoney}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Anton"]
  s.date = %q{2011-03-01}
  s.description = %q{Webmoney}
  s.email = %q{eagle.anton@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/oa-webmoney.rb",
    "lib/oa-webmoney/webmoney.rb",
    "oa-webmoney.gemspec",
    "spec/oa-webmoney_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/skyeagle/oa-webmoney}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Webmoney}
  s.test_files = [
    "spec/oa-webmoney_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<webmoney>, ["~> 0.0.10"])
      s.add_runtime_dependency(%q<webmoney>, ["~> 0.0.10"])
      s.add_development_dependency(%q<rspec>, ["> 2.5.02.5.0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<webmoney>, ["~> 0.0.10"])
      s.add_dependency(%q<webmoney>, ["~> 0.0.10"])
      s.add_dependency(%q<rspec>, ["> 2.5.02.5.0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<webmoney>, ["~> 0.0.10"])
    s.add_dependency(%q<webmoney>, ["~> 0.0.10"])
    s.add_dependency(%q<rspec>, ["> 2.5.02.5.0"])
  end
end

