# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "oa-webmoney"
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Anton"]
  s.date = "2011-12-08"
  s.description = "Webmoney"
  s.email = "eagle.anton@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "lib/oa-webmoney.rb",
    "lib/oa-webmoney/webmoney.rb",
    "oa-webmoney.gemspec",
    "spec/oa-webmoney_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/skyeagle/oa-webmoney"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Webmoney"
  s.test_files = [
    "spec/oa-webmoney_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<webmoney>, ["~> 0.0.10"])
      s.add_runtime_dependency(%q<webmoney>, ["~> 0.0.10"])
      s.add_development_dependency(%q<rspec>, ["> 2.5.02.5.0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<webmoney>, ["~> 0.0.10"])
      s.add_dependency(%q<webmoney>, ["~> 0.0.10"])
      s.add_dependency(%q<rspec>, ["> 2.5.02.5.0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<webmoney>, ["~> 0.0.10"])
    s.add_dependency(%q<webmoney>, ["~> 0.0.10"])
    s.add_dependency(%q<rspec>, ["> 2.5.02.5.0"])
  end
end

